name: environment-1

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Deployed to Test
        run: |
          echo "username = ${{ vars.USERNAME }}"
          echo "password = ${{ secrets.PASSWORD }}"

  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deployed to Dev
        run: |
          echo "username = ${{ vars.USERNAME }}"
          echo "password = ${{ secrets.PASSWORD }}"

  stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Deployed to Stage
        run: |
          echo "username = ${{ vars.USERNAME }}"
          echo "password = ${{ secrets.PASSWORD }}"

  prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deployed to Prod
        run: |
          echo "username = ${{ vars.USERNAME }}"
          echo "password = ${{ secrets.PASSWORD }}"

