name: environment

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
      steps:
        - name: test
          run: echo " deploy to test"
               echo "username = ${{vars.username}}"
               echo "password = ${{secrate.password}}"


  dev:
    runs-on: ubuntu-latest
    needs: test
    environment: dev
      steps:
         - name: dev
           run:
              echo "deploy to dev"
              echo "username = ${{vars.username}}"
              echo "password = ${{secrate.password}}"

  stage:
    runs-on: ubuntu-latest
    needs: dev
    environment: stage
      steps:
        - name: stage
          run:
            echo "deploy to stage"
            echo "username = ${{vars.username}}"
            echo "password = ${{secrate.password}}"

  prod:
    runs-on: ubuntu-latest
    needs: prod
    environment: prod
      steps:
        - name: prod
          run:
            echo "depolyed  to prod"
            echo "username = ${{vars.username}}"
            echo "password = ${{secrate.password}}"
            
    
